### ISSUE TITLE
Player X goes first all the time

### ISSUE THREAD

**Issue by dkim286** [dkim286/cpsc362-proj#3]
Expected behavior: 

- Player X goes first initially 
- After each game, the previous loser gets to go first 

Current behavior: 

- Player X goes first regardless of who won the last round

**Comment by kavyavandana** [comment]
Does this mean we would have to maintain the game state somewhere even after the game ends? @dkim286

**Comment by dkim286** [comment]
No. `Game.reset_game()` just has to set the `_player` variable to whoever just lost.

**Comment by davidqdo** [comment]
About this issue, on the scenario when there is a tie, do you want the other player who did not go first to go first the next game?

**Comment by dkim286** [comment]
that's a good idea, yes.

**Comment by davidqdo** [comment]
alright i'll push what I have and you can try it out

**Comment by dkim286** [comment]
resolved by https://github.com/dkim286/cpsc362-proj/commit/a315a57bcf95166562b58b32fae247c8bf3db885
