### ISSUE TITLE
Splash screen does not load at runtime 

### ISSUE THREAD

**Issue by dkim286** [dkim286/cpsc362-proj#5]
Expected behavior: 

- There should be a splash screen visible when the game's UI initializes

Current behavior: 

- There's no splash screen visible when the game's UI initializes 

Possible causes: 

- Is the PyGame rendering function not being called after loading the splash screen image? 
- Is the game not waiting for a few seconds (`time.sleep(n)`) after loading up the splash screen? 
- Is the splash screen image being not loaded?

**Comment by davidqdo** [comment]
Fixed this not showing up

**Comment by dkim286** [comment]
Resolved by https://github.com/dkim286/cpsc362-proj/commit/e1c4c2d30810231b7eb6f30fab9534a9b77080fd
