### ISSUE TITLE
improbable, but not impossible chance of infinite recursion in  cpu.py 

### ISSUE THREAD

**Issue by dkim286** [dkim286/cpsc362-proj#8]
from: https://github.com/dkim286/cpsc362-proj/commit/9f430903bcfb2dc6be33493843de1b5535b0b8ec#comments

https://github.com/dkim286/cpsc362-proj/blob/04ebd365ec986eaa30f9cfbb5637ce347e9d1bd5/ttt/cpu.py#L37-L43

we could use `random.sample([1, 2, 3], 3)` instead: 

https://docs.python.org/3.8/library/random.html#random.sample

Something like this, maybe (not tested): 

```python
rand_rows = random.sample([1, 2, 3], 3)
rand_rows = random.sample([1, 2, 3], 3)
move_found = False

for row in rand_rows: 
    for col in rand_cols: 
        if self._game.place_move(row, col):
            move_found = True
            break
    if move_found:
        break 
```

**Comment by kavyavandana** [comment]
Thanks for creating this issue. This isnt an elegant solution but works. There would be like, (1 * 3!) iterations every worst case scenario? Tested this and solution works locally.

**Comment by kavyavandana** [comment]
sorry my bad. strike the 1 * 3! iterations. this works fine.

**Comment by kavyavandana** [comment]
https://github.com/dkim286/cpsc362-proj/commit/86e13d576075f16bec203750308fb868866a403e

**Comment by kavyavandana** [comment]
Please review and let me know if this looks okay. thank you.

**Comment by dkim286** [comment]
causes issue https://github.com/dkim286/cpsc362-proj/issues/9

**Comment by dkim286** [comment]
resolved by https://github.com/dkim286/cpsc362-proj/commit/874f732fe762fd9e12aa0db0d6242f4499bd031f
